### ISSUE TITLE
Can I get rid of Ansible?

### ISSUE THREAD

**Issue by akhil-naidu** [dokku/omakase#1]
It is not like I don't want to use Ansible. I want to know whether the `omakase` have the necessary builds within it to execute a `.yml`

I'm working on a project where I control multiple dokku instances via Ansible. Not to keep all the dokku instances in sync, but to execute dokku commands in remote systems via (Nodejs and Ansible). The problem I'm facing was, there is no buildpack for Ansible, so if I rebuild my Node App, I should reinstall Ansible.

> If you like to know more details, I can provide them.  Also, I would like to know more about omakase to implement it in my project.

**Comment by akhil-naidu** [comment]
> To provide a bit more detail, consider this case. 

It's not the place to explain the entire architecture of my web app(t2d), but assume that t2d aka Talk to Dokku has a web dashboard through which users can manage their dokku and dokku apps hosted in their own VPS.

Now, when the user clicks on a button => `delete` app. Presently I'm using NodeJS to execute an ansible command in the remote system: `ansible-playbook playbook.yml -e "appTitle=forem"--tags delete-app`

Contents of `playbook.yml`
```
---
- hosts: nodes
  roles:
    - dokku_bot.ansible_dokku

  tasks:
    - name: Delete that app
      dokku_app:
        app: "{{ appTitle }}"
        state: absent
      tags: delete-app
```

---

What I want to know is 
- whether I can achieve this without the usage of tags and roles? or 
- In what ways does Omakase handle this?
